version: "3"
services:

  pycbox:
    build: .
    init: true
    restart: always
    volumes:
      - ./pycbox:/pycbox/pycbox
      - ./files:/pycbox/files
    ports:
      - "5000:5000"
    environment:
      - PYCBOX_CONFIG=config.yml
    cap_drop:
      - all
    cap_add:
      - chown
      - setgid
      - setuid
