version: "3"
services:

  picbox:
    build: .
    restart: always
    volumes:
      - ./pycbox:/pycbox/pycbox
      - ./files:/pycbox/files
    ports:
      - "5000:5000"
    environment:
      - PYCBOX_CONFIG=config.yml
    cap_drop:
      - all
